services:
  - type: web
    name: dti-cpms
    runtime: python3
    buildCommand: echo "BUILD TEMPORARILY DISABLED FOR MAINTENANCE" && exit 1
    startCommand: bash deploy.sh
    env:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTHONUNBUFFERED
        value: 1
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: false
      - key: STREAMLIT_SERVER_ENABLE_STATIC_SERVING
        value: true
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: false
