[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
enableStaticServing = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
primaryColor = "#172087"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[client]
toolbarMode = "minimal"
showErrorDetails = true
caching = true
