# Enhanced Security Configuration Template for DTI CPMS Production
# Copy this to .streamlit/secrets.toml and customize for your deployment

# Admin Configuration (Required)
[admin]
username = "admin"
password = "dtidcfocpms2025"  # Change this to a strong password
email = "admin@dti.gov.ph"
first_name = "DTI"
last_name = "Administrator"

# Email Configuration (Required for notifications)
[email]
sender_email = "your-email@gmail.com"
sender_password = "your-app-password"  # Use App Password for Gmail
smtp_server = "smtp.gmail.com"
smtp_port = 587

# Security Configuration (Enhanced)
[security]
# Session settings
session_timeout_hours = "8"
max_failed_logins = "5"
login_rate_limit_minutes = "15"

# Password requirements
min_password_length = "8"
require_strong_passwords = "true"

# File upload security
max_file_size_mb = "50"
allowed_file_types = ".xlsx,.xls,.csv,.pdf,.jpg,.png"

# Logging and monitoring
log_retention_days = "90"
enable_audit_logging = "true"

# Environment settings
environment = "production"  # or "development"
debug_mode = "false"

# Database/Storage encryption (future use)
[encryption]
# encryption_key = "generate-a-random-32-byte-key"  # For future file encryption

# Rate limiting and DDoS protection
[protection]
max_requests_per_minute = "60"
max_requests_per_hour = "1000"
block_suspicious_ips = "true"

# Monitoring and alerts
[monitoring]
enable_email_alerts = "true"
alert_email = "security@dti.gov.ph"
failed_login_threshold = "10"  # Alert after N failed logins

# Add any other sensitive configurations here
# Never commit this file to GitHub!
